In [1]:
dict_of_lists = {
    "name":["Ginger", "Scout", "Barney", "Buddy"],
    "breed":["Dachshund","Dalmatian","French Bulldog","Maltese"],
    "height":[22,59,30,19],
    "weight":[10,25,24,8],
    "date_of_birth":["2019-03-14", "2008-03-23", "2010-04-10", "2016-04-21"]
}
print (dict_of_lists)

{'name': ['Ginger', 'Scout', 'Barney', 'Buddy'], 'breed': ['Dachshund', 'Dalmatian', 'French Bulldog', 'Maltese'], 'height': [22, 59, 30, 19], 'weight': [10, 25, 24, 8], 'date_of_birth': ['2019-03-14', '2008-03-23', '2010-04-10', '2016-04-21']}

In [2]:
list_of_dicts = [
    {"name":"Ginger", "breed":"Dachshund", "height":22, "weight": 10, "date_of_birth":"2019-03-14"},
    {"name":"Barney", "breed":"French Bulldog", "height":30, "weight": 24, "date_of_birth":"2010-04-10"},
    {"name":"Butch", "breed":"French Bulldog", "height":28, "weight": 22, "date_of_birth":"2014-08-07"},
    {"name":"Buddy", "breed":"Maltese", "height":19, "weight": 8, "date_of_birth":"2016-04-21"},
]
print(list_of_dicts)

[{'name': 'Ginger', 'breed': 'Dachshund', 'height': 22, 'weight': 10, 'date_of_birth': '2019-03-14'}, {'name': 'Barney', 'breed': 'French Bulldog', 'height': 30, 'weight': 24, 'date_of_birth': '2010-04-10'}, {'name': 'Butch', 'breed': 'French Bulldog', 'height': 28, 'weight': 22, 'date_of_birth': '2014-08-07'}, {'name': 'Buddy', 'breed': 'Maltese', 'height': 19, 'weight': 8, 'date_of_birth': '2016-04-21'}]

In [3]:
import pandas as pd

In [4]:
df_dict_columns = pd.DataFrame.from_dict(dict_of_lists)
print(df_dict_columns)

     name           breed  height  weight date_of_birth
0  Ginger       Dachshund      22      10    2019-03-14
1   Scout       Dalmatian      59      25    2008-03-23
2  Barney  French Bulldog      30      24    2010-04-10
3   Buddy         Maltese      19       8    2016-04-21

In [5]:
df_dict_columns = pd.DataFrame(dict_of_lists)
print(df_dict_columns)

     name           breed  height  weight date_of_birth
0  Ginger       Dachshund      22      10    2019-03-14
1   Scout       Dalmatian      59      25    2008-03-23
2  Barney  French Bulldog      30      24    2010-04-10
3   Buddy         Maltese      19       8    2016-04-21

In [10]:
df_dict_index = pd.DataFrame.from_dict(dict_of_lists, orient="index")
print(df_dict_index)

                        0           1               2           3
name               Ginger       Scout          Barney       Buddy
breed           Dachshund   Dalmatian  French Bulldog     Maltese
height                 22          59              30          19
weight                 10          25              24           8
date_of_birth  2019-03-14  2008-03-23      2010-04-10  2016-04-21

In [11]:
file = '04.05_05.06.csv'
df = pd.read_csv(file)

print(df.head())

  Distance from Kottas Unnamed: 1 Unnamed: 2 Unnamed: 3          Unnamed: 4  \
0                 (km)  DiffSnow1  DiffSnow2  DiffSnow3  DiffSnowMean_95-97
1                    0        NaN         61         41                  51
2                  0.5        NaN        NaN        NaN             #DIV/0!
3                    1         26        NaN        NaN                  26
4                  1.5         36         37        NaN                36.5

  Cluster +150/-20 Cluster +150/-10 Cluster +200/0  Unnamed: 8  AccumulationI  \
0              NaN              NaN            NaN         NaN            NaN
1               51               51             51         NaN     202.575000
2          #DIV/0!          #DIV/0!        #DIV/0!         NaN            NaN
3               26               26             26         NaN     103.273529
4             36.5             36.5           36.5         NaN     144.980147

   AccumulationII  AccumulationIII  AccumulationIV  Schneedichte  Unnamed: 14  \
0             NaN              NaN             NaN           NaN       Time/a
1      202.575000       202.575000      202.575000         370.0  0.931506849
2             NaN              NaN             NaN         370.0  0.931506849
3      103.273529       103.273529      103.273529         370.0  0.931506849
4      144.980147       144.980147      144.980147         370.0  0.931506849

   Unnamed: 15 mean/without mean/cluster_1 mean/cluster_2mean/cluster_3  \
0          NaN          NaN            NaN                          NaN
1          NaN          NaN            NaN                          NaN
2          NaN          NaN            NaN                          NaN
3          NaN          NaN            NaN                          NaN
4          NaN          NaN            NaN                          NaN

  Unnamed: 19
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN

In [19]:

file = '04.05_05.06.csv'

# Define what missing values are
missing_values = ["(km)", "DiffSnow1", "DiffSnow2", "DiffSnow3", "DiffSnowMean_95-97", "#DIV/0!", "Time/a"]

#Read the file into a DataFrame(df2), skip first row, search for missing values and rename the columns
df2 = pd.read_csv(file, skiprows = 1, na_values = missing_values, names = ['Distance_km', 'HeightChange1','HeightChange2', 'HeightChange3','HeightChange4', 'Filter1', 'Filter2','Filter3', 'unknown_1', 'Accumulation_1','Accumulation_2', 'Accumulation_3','Accumulation_4', 'Snow_Density', 'Time_a','mean_without', 'mean_Filter1', 'mean_Filter2', 'mean_Filter3', 'unknown_2'])

# View the head of the DataFrame
print(df2.head())

   Distance_km  HeightChange1  HeightChange2  HeightChange3  HeightChange4  \
0          NaN            NaN            NaN            NaN            NaN
1          0.0            NaN           61.0           41.0           51.0
2          0.5            NaN            NaN            NaN            NaN
3          1.0           26.0            NaN            NaN           26.0
4          1.5           36.0           37.0            NaN           36.5

   Filter1  Filter2  Filter3  unknown_1  Accumulation_1  Accumulation_2  \
0      NaN      NaN      NaN        NaN             NaN             NaN
1     51.0     51.0     51.0        NaN      202.575000      202.575000
2      NaN      NaN      NaN        NaN             NaN             NaN
3     26.0     26.0     26.0        NaN      103.273529      103.273529
4     36.5     36.5     36.5        NaN      144.980147      144.980147

   Accumulation_3  Accumulation_4  Snow_Density    Time_a  mean_without  \
0             NaN             NaN           NaN       NaN           NaN
1      202.575000      202.575000         370.0  0.931507           NaN
2             NaN             NaN         370.0  0.931507           NaN
3      103.273529      103.273529         370.0  0.931507           NaN
4      144.980147      144.980147         370.0  0.931507           NaN

   mean_Filter1  mean_Filter2  mean_Filter3  unknown_2
0           NaN           NaN           NaN        NaN
1           NaN           NaN           NaN        NaN
2           NaN           NaN           NaN        NaN
3           NaN           NaN           NaN        NaN
4           NaN           NaN           NaN        NaN

In [18]:
sort_df2 = df2.sort_values("Distance_km")
print(sort_df2.head())

   Distance_km  HeightChange1  HeightChange2  HeightChange3  HeightChange4  \
1          0.0            NaN           61.0           41.0           51.0
2          0.5            NaN            NaN            NaN            NaN
3          1.0           26.0            NaN            NaN           26.0
4          1.5           36.0           37.0            NaN           36.5
5          2.0           75.0           68.0            NaN           71.5

   Filter1  Filter2  Filter3  unknown_1  Accumulation_1  Accumulation_2  \
1     51.0     51.0     51.0        NaN      202.575000      202.575000
2      NaN      NaN      NaN        NaN             NaN             NaN
3     26.0     26.0     26.0        NaN      103.273529      103.273529
4     36.5     36.5     36.5        NaN      144.980147      144.980147
5     71.5     71.5     71.5        NaN      284.002206      284.002206

   Accumulation_3  Accumulation_4  Snow_Density    Time_a  mean_without  \
1      202.575000      202.575000         370.0  0.931507           NaN
2             NaN             NaN         370.0  0.931507           NaN
3      103.273529      103.273529         370.0  0.931507           NaN
4      144.980147      144.980147         370.0  0.931507           NaN
5      284.002206      284.002206         370.0  0.931507           NaN

   mean_Filter1  mean_Filter2  mean_Filter3  unknown_2
1           NaN           NaN           NaN        NaN
2           NaN           NaN           NaN        NaN
3           NaN           NaN           NaN        NaN
4           NaN           NaN           NaN        NaN
5           NaN           NaN           NaN        NaN

In [20]:
file = 'DAuV.xlsx'
data = pd.ExcelFile(file)
df1 = data.parse("1994") 
df1 = data.parse(0, skiprows=[0], names=['Area', 'Height','Standart_Deviation', 'Median','Period_S', 'Period_E', 'Duration','Density', 'Accumulation'])

#Adding new rows from other sources, check for the new rows in the output
df2["Area"] = df1["Area"]
df2["Area1"] = df1["Area"]
df2["New_row"] = 2*df1["Standart_Deviation"]
df2

,Distance_km,HeightChange1,HeightChange2,HeightChange3,HeightChange4,Filter1,Filter2,Filter3,unknown_1,Accumulation_1,...,Snow_Density,Time_a,mean_without,mean_Filter1,mean_Filter2,mean_Filter3,unknown_2,Area,Area1,New_row
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pegelfeld,Pegelfeld,NaN
1,0.0,NaN,61.0,41.0,51.0,51.0,51.0,51.0,NaN,202.575000,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,km70/B30,km70/B30,71.170043
2,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,B30/100vWasa,B30/100vWasa,84.874262
3,1.0,26.0,NaN,NaN,26.0,26.0,26.0,26.0,NaN,103.273529,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,55vWasa,55vWasa,41.907371
4,1.5,36.0,37.0,NaN,36.5,36.5,36.5,36.5,NaN,144.980147,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,Abzweig Wasa,Abzweig Wasa,23.046809
5,2.0,75.0,68.0,NaN,71.5,71.5,71.5,71.5,NaN,284.002206,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,45nWasa,45nWasa,23.852854
6,2.5,71.0,77.0,NaN,74.0,74.0,74.0,74.0,NaN,293.932353,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,Kottas Camp,Kottas Camp,20.237950
7,3.0,60.0,NaN,NaN,60.0,60.0,60.0,60.0,NaN,238.323529,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,Strommebakken,Strommebakken,41.778100
8,3.5,50.0,NaN,NaN,50.0,50.0,50.0,50.0,NaN,198.602941,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,EndeTrasse,EndeTrasse,62.285441
9,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,370.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,4.5,71.0,NaN,NaN,71.0,71.0,71.0,71.0,NaN,282.016177,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,5.0,3.0,-40.0,NaN,-18.5,-18.5,NaN,NaN,NaN,-73.483088,...,370.0,0.931507,NaN,186.024755,186.024755,218.463235,218.463235,NaN,NaN,NaN
12,5.5,28.0,NaN,NaN,28.0,28.0,28.0,28.0,NaN,111.217647,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,6.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,NaN,7.944118,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,6.5,91.0,NaN,NaN,91.0,91.0,91.0,91.0,NaN,361.457353,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,7.0,81.0,81.0,NaN,81.0,81.0,81.0,81.0,NaN,321.736765,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,7.5,49.0,48.0,NaN,48.5,48.5,48.5,48.5,NaN,192.644853,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,8.0,59.0,NaN,NaN,59.0,59.0,59.0,59.0,NaN,234.351471,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,8.5,76.0,73.0,NaN,74.5,74.5,74.5,74.5,NaN,295.918382,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,9.0,72.0,70.0,NaN,71.0,71.0,71.0,71.0,NaN,282.016177,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,9.5,87.0,NaN,NaN,87.0,87.0,87.0,87.0,NaN,345.569118,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,10.0,77.0,NaN,NaN,77.0,77.0,77.0,77.0,NaN,305.848529,...,370.0,0.931507,NaN,245.870441,245.870441,245.870441,245.870441,NaN,NaN,NaN
22,10.5,76.0,NaN,NaN,76.0,76.0,76.0,76.0,NaN,301.876471,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,11.0,80.0,NaN,NaN,80.0,80.0,80.0,80.0,NaN,317.764706,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,11.5,77.0,NaN,NaN,77.0,77.0,77.0,77.0,NaN,305.848529,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,12.0,80.0,NaN,NaN,80.0,80.0,80.0,80.0,NaN,317.764706,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,12.5,79.0,72.0,NaN,75.5,75.5,75.5,75.5,NaN,299.890441,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,13.0,79.0,72.0,NaN,75.5,75.5,75.5,75.5,NaN,299.890441,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,13.5,86.0,NaN,NaN,86.0,86.0,86.0,86.0,NaN,341.597059,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,14.0,82.0,NaN,NaN,82.0,82.0,82.0,82.0,NaN,325.708823,...,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,436.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
874,436.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
875,437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
876,437.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877,438.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
878,438.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
879,439.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
880,439.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
881,440.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
882,440.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
883,441.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
884,441.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885,442.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
886,442.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
887,443.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
888,443.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
889,444.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
890,444.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
891,445.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
892,445.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
893,446.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
894,446.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
895,447.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
896,447.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897,448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
898,448.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
899,449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
900,449.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
901,450.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# Delete a single column
df3 = df2.drop("Area1", axis = 1) #When deleting columns, the index = 1, when deleting rows it must be set index=0
df3

,Distance_km,HeightChange1,HeightChange2,HeightChange3,HeightChange4,Filter1,Filter2,Filter3,unknown_1,Accumulation_1,...,Accumulation_4,Snow_Density,Time_a,mean_without,mean_Filter1,mean_Filter2,mean_Filter3,unknown_2,Area,New_row
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pegelfeld,NaN
1,0.0,NaN,61.0,41.0,51.0,51.0,51.0,51.0,NaN,202.575000,...,202.575000,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,km70/B30,71.170043
2,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,B30/100vWasa,84.874262
3,1.0,26.0,NaN,NaN,26.0,26.0,26.0,26.0,NaN,103.273529,...,103.273529,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,55vWasa,41.907371
4,1.5,36.0,37.0,NaN,36.5,36.5,36.5,36.5,NaN,144.980147,...,144.980147,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,Abzweig Wasa,23.046809
5,2.0,75.0,68.0,NaN,71.5,71.5,71.5,71.5,NaN,284.002206,...,284.002206,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,45nWasa,23.852854
6,2.5,71.0,77.0,NaN,74.0,74.0,74.0,74.0,NaN,293.932353,...,293.932353,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,Kottas Camp,20.237950
7,3.0,60.0,NaN,NaN,60.0,60.0,60.0,60.0,NaN,238.323529,...,238.323529,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,Strommebakken,41.778100
8,3.5,50.0,NaN,NaN,50.0,50.0,50.0,50.0,NaN,198.602941,...,198.602941,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,EndeTrasse,62.285441
9,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,370.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,4.5,71.0,NaN,NaN,71.0,71.0,71.0,71.0,NaN,282.016177,...,282.016177,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,5.0,3.0,-40.0,NaN,-18.5,-18.5,NaN,NaN,NaN,-73.483088,...,NaN,370.0,0.931507,NaN,186.024755,186.024755,218.463235,218.463235,NaN,NaN
12,5.5,28.0,NaN,NaN,28.0,28.0,28.0,28.0,NaN,111.217647,...,111.217647,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,6.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,NaN,7.944118,...,7.944118,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,6.5,91.0,NaN,NaN,91.0,91.0,91.0,91.0,NaN,361.457353,...,361.457353,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,7.0,81.0,81.0,NaN,81.0,81.0,81.0,81.0,NaN,321.736765,...,321.736765,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,7.5,49.0,48.0,NaN,48.5,48.5,48.5,48.5,NaN,192.644853,...,192.644853,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,8.0,59.0,NaN,NaN,59.0,59.0,59.0,59.0,NaN,234.351471,...,234.351471,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,8.5,76.0,73.0,NaN,74.5,74.5,74.5,74.5,NaN,295.918382,...,295.918382,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,9.0,72.0,70.0,NaN,71.0,71.0,71.0,71.0,NaN,282.016177,...,282.016177,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,9.5,87.0,NaN,NaN,87.0,87.0,87.0,87.0,NaN,345.569118,...,345.569118,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,10.0,77.0,NaN,NaN,77.0,77.0,77.0,77.0,NaN,305.848529,...,305.848529,370.0,0.931507,NaN,245.870441,245.870441,245.870441,245.870441,NaN,NaN
22,10.5,76.0,NaN,NaN,76.0,76.0,76.0,76.0,NaN,301.876471,...,301.876471,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,11.0,80.0,NaN,NaN,80.0,80.0,80.0,80.0,NaN,317.764706,...,317.764706,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,11.5,77.0,NaN,NaN,77.0,77.0,77.0,77.0,NaN,305.848529,...,305.848529,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,12.0,80.0,NaN,NaN,80.0,80.0,80.0,80.0,NaN,317.764706,...,317.764706,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,12.5,79.0,72.0,NaN,75.5,75.5,75.5,75.5,NaN,299.890441,...,299.890441,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,13.0,79.0,72.0,NaN,75.5,75.5,75.5,75.5,NaN,299.890441,...,299.890441,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,13.5,86.0,NaN,NaN,86.0,86.0,86.0,86.0,NaN,341.597059,...,341.597059,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,14.0,82.0,NaN,NaN,82.0,82.0,82.0,82.0,NaN,325.708823,...,325.708823,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,436.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
874,436.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
875,437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
876,437.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877,438.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
878,438.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
879,439.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
880,439.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
881,440.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
882,440.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
883,441.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
884,441.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885,442.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
886,442.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
887,443.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
888,443.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
889,444.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
890,444.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
891,445.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
892,445.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
893,446.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
894,446.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
895,447.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
896,447.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897,448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
898,448.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
899,449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
900,449.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
901,450.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
# Delete multiple columns
df4 = df3.drop(["unknown_1", "unknown_2"], axis=1)
df4

,Distance_km,HeightChange1,HeightChange2,HeightChange3,HeightChange4,Filter1,Filter2,Filter3,Accumulation_1,Accumulation_2,Accumulation_3,Accumulation_4,Snow_Density,Time_a,mean_without,mean_Filter1,mean_Filter2,mean_Filter3,Area,New_row
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pegelfeld,NaN
1,0.0,NaN,61.0,41.0,51.0,51.0,51.0,51.0,202.575000,202.575000,202.575000,202.575000,370.0,0.931507,NaN,NaN,NaN,NaN,km70/B30,71.170043
2,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370.0,0.931507,NaN,NaN,NaN,NaN,B30/100vWasa,84.874262
3,1.0,26.0,NaN,NaN,26.0,26.0,26.0,26.0,103.273529,103.273529,103.273529,103.273529,370.0,0.931507,NaN,NaN,NaN,NaN,55vWasa,41.907371
4,1.5,36.0,37.0,NaN,36.5,36.5,36.5,36.5,144.980147,144.980147,144.980147,144.980147,370.0,0.931507,NaN,NaN,NaN,NaN,Abzweig Wasa,23.046809
5,2.0,75.0,68.0,NaN,71.5,71.5,71.5,71.5,284.002206,284.002206,284.002206,284.002206,370.0,0.931507,NaN,NaN,NaN,NaN,45nWasa,23.852854
6,2.5,71.0,77.0,NaN,74.0,74.0,74.0,74.0,293.932353,293.932353,293.932353,293.932353,370.0,0.931507,NaN,NaN,NaN,NaN,Kottas Camp,20.237950
7,3.0,60.0,NaN,NaN,60.0,60.0,60.0,60.0,238.323529,238.323529,238.323529,238.323529,370.0,0.931507,NaN,NaN,NaN,NaN,Strommebakken,41.778100
8,3.5,50.0,NaN,NaN,50.0,50.0,50.0,50.0,198.602941,198.602941,198.602941,198.602941,370.0,0.931507,NaN,NaN,NaN,NaN,EndeTrasse,62.285441
9,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,4.5,71.0,NaN,NaN,71.0,71.0,71.0,71.0,282.016177,282.016177,282.016177,282.016177,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
11,5.0,3.0,-40.0,NaN,-18.5,-18.5,NaN,NaN,-73.483088,-73.483088,NaN,NaN,370.0,0.931507,NaN,186.024755,186.024755,218.463235,NaN,NaN
12,5.5,28.0,NaN,NaN,28.0,28.0,28.0,28.0,111.217647,111.217647,111.217647,111.217647,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
13,6.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,7.944118,7.944118,7.944118,7.944118,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
14,6.5,91.0,NaN,NaN,91.0,91.0,91.0,91.0,361.457353,361.457353,361.457353,361.457353,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
15,7.0,81.0,81.0,NaN,81.0,81.0,81.0,81.0,321.736765,321.736765,321.736765,321.736765,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
16,7.5,49.0,48.0,NaN,48.5,48.5,48.5,48.5,192.644853,192.644853,192.644853,192.644853,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
17,8.0,59.0,NaN,NaN,59.0,59.0,59.0,59.0,234.351471,234.351471,234.351471,234.351471,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
18,8.5,76.0,73.0,NaN,74.5,74.5,74.5,74.5,295.918382,295.918382,295.918382,295.918382,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
19,9.0,72.0,70.0,NaN,71.0,71.0,71.0,71.0,282.016177,282.016177,282.016177,282.016177,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
20,9.5,87.0,NaN,NaN,87.0,87.0,87.0,87.0,345.569118,345.569118,345.569118,345.569118,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
21,10.0,77.0,NaN,NaN,77.0,77.0,77.0,77.0,305.848529,305.848529,305.848529,305.848529,370.0,0.931507,NaN,245.870441,245.870441,245.870441,NaN,NaN
22,10.5,76.0,NaN,NaN,76.0,76.0,76.0,76.0,301.876471,301.876471,301.876471,301.876471,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
23,11.0,80.0,NaN,NaN,80.0,80.0,80.0,80.0,317.764706,317.764706,317.764706,317.764706,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
24,11.5,77.0,NaN,NaN,77.0,77.0,77.0,77.0,305.848529,305.848529,305.848529,305.848529,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
25,12.0,80.0,NaN,NaN,80.0,80.0,80.0,80.0,317.764706,317.764706,317.764706,317.764706,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
26,12.5,79.0,72.0,NaN,75.5,75.5,75.5,75.5,299.890441,299.890441,299.890441,299.890441,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
27,13.0,79.0,72.0,NaN,75.5,75.5,75.5,75.5,299.890441,299.890441,299.890441,299.890441,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
28,13.5,86.0,NaN,NaN,86.0,86.0,86.0,86.0,341.597059,341.597059,341.597059,341.597059,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
29,14.0,82.0,NaN,NaN,82.0,82.0,82.0,82.0,325.708823,325.708823,325.708823,325.708823,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,436.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
874,436.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
875,437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
876,437.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877,438.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
878,438.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
879,439.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
880,439.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
881,440.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
882,440.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
883,441.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
884,441.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885,442.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
886,442.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
887,443.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
888,443.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
889,444.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
890,444.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
891,445.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
892,445.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
893,446.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
894,446.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
895,447.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
896,447.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897,448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
898,448.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
899,449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
900,449.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
901,450.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
#Delete a row
df5=df4.drop(0, axis = 0)
df5

,Distance_km,HeightChange1,HeightChange2,HeightChange3,HeightChange4,Filter1,Filter2,Filter3,Accumulation_1,Accumulation_2,Accumulation_3,Accumulation_4,Snow_Density,Time_a,mean_without,mean_Filter1,mean_Filter2,mean_Filter3,Area,New_row
1,0.0,NaN,61.0,41.0,51.0,51.0,51.0,51.0,202.575000,202.575000,202.575000,202.575000,370.0,0.931507,NaN,NaN,NaN,NaN,km70/B30,71.170043
2,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370.0,0.931507,NaN,NaN,NaN,NaN,B30/100vWasa,84.874262
3,1.0,26.0,NaN,NaN,26.0,26.0,26.0,26.0,103.273529,103.273529,103.273529,103.273529,370.0,0.931507,NaN,NaN,NaN,NaN,55vWasa,41.907371
4,1.5,36.0,37.0,NaN,36.5,36.5,36.5,36.5,144.980147,144.980147,144.980147,144.980147,370.0,0.931507,NaN,NaN,NaN,NaN,Abzweig Wasa,23.046809
5,2.0,75.0,68.0,NaN,71.5,71.5,71.5,71.5,284.002206,284.002206,284.002206,284.002206,370.0,0.931507,NaN,NaN,NaN,NaN,45nWasa,23.852854
6,2.5,71.0,77.0,NaN,74.0,74.0,74.0,74.0,293.932353,293.932353,293.932353,293.932353,370.0,0.931507,NaN,NaN,NaN,NaN,Kottas Camp,20.237950
7,3.0,60.0,NaN,NaN,60.0,60.0,60.0,60.0,238.323529,238.323529,238.323529,238.323529,370.0,0.931507,NaN,NaN,NaN,NaN,Strommebakken,41.778100
8,3.5,50.0,NaN,NaN,50.0,50.0,50.0,50.0,198.602941,198.602941,198.602941,198.602941,370.0,0.931507,NaN,NaN,NaN,NaN,EndeTrasse,62.285441
9,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,4.5,71.0,NaN,NaN,71.0,71.0,71.0,71.0,282.016177,282.016177,282.016177,282.016177,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
11,5.0,3.0,-40.0,NaN,-18.5,-18.5,NaN,NaN,-73.483088,-73.483088,NaN,NaN,370.0,0.931507,NaN,186.024755,186.024755,218.463235,NaN,NaN
12,5.5,28.0,NaN,NaN,28.0,28.0,28.0,28.0,111.217647,111.217647,111.217647,111.217647,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
13,6.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,7.944118,7.944118,7.944118,7.944118,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
14,6.5,91.0,NaN,NaN,91.0,91.0,91.0,91.0,361.457353,361.457353,361.457353,361.457353,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
15,7.0,81.0,81.0,NaN,81.0,81.0,81.0,81.0,321.736765,321.736765,321.736765,321.736765,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
16,7.5,49.0,48.0,NaN,48.5,48.5,48.5,48.5,192.644853,192.644853,192.644853,192.644853,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
17,8.0,59.0,NaN,NaN,59.0,59.0,59.0,59.0,234.351471,234.351471,234.351471,234.351471,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
18,8.5,76.0,73.0,NaN,74.5,74.5,74.5,74.5,295.918382,295.918382,295.918382,295.918382,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
19,9.0,72.0,70.0,NaN,71.0,71.0,71.0,71.0,282.016177,282.016177,282.016177,282.016177,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
20,9.5,87.0,NaN,NaN,87.0,87.0,87.0,87.0,345.569118,345.569118,345.569118,345.569118,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
21,10.0,77.0,NaN,NaN,77.0,77.0,77.0,77.0,305.848529,305.848529,305.848529,305.848529,370.0,0.931507,NaN,245.870441,245.870441,245.870441,NaN,NaN
22,10.5,76.0,NaN,NaN,76.0,76.0,76.0,76.0,301.876471,301.876471,301.876471,301.876471,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
23,11.0,80.0,NaN,NaN,80.0,80.0,80.0,80.0,317.764706,317.764706,317.764706,317.764706,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
24,11.5,77.0,NaN,NaN,77.0,77.0,77.0,77.0,305.848529,305.848529,305.848529,305.848529,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
25,12.0,80.0,NaN,NaN,80.0,80.0,80.0,80.0,317.764706,317.764706,317.764706,317.764706,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
26,12.5,79.0,72.0,NaN,75.5,75.5,75.5,75.5,299.890441,299.890441,299.890441,299.890441,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
27,13.0,79.0,72.0,NaN,75.5,75.5,75.5,75.5,299.890441,299.890441,299.890441,299.890441,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
28,13.5,86.0,NaN,NaN,86.0,86.0,86.0,86.0,341.597059,341.597059,341.597059,341.597059,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
29,14.0,82.0,NaN,NaN,82.0,82.0,82.0,82.0,325.708823,325.708823,325.708823,325.708823,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
30,14.5,89.0,91.0,NaN,90.0,90.0,90.0,90.0,357.485294,357.485294,357.485294,357.485294,370.0,0.931507,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,436.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
874,436.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
875,437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
876,437.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877,438.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
878,438.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
879,439.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
880,439.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
881,440.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
882,440.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
883,441.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
884,441.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
885,442.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
886,442.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
887,443.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
888,443.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
889,444.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
890,444.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
891,445.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
892,445.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
893,446.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
894,446.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
895,447.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
896,447.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897,448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
898,448.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
899,449.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
900,449.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
901,450.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# Dropping duplicates
test = df4.drop_duplicates(subset = ["Snow_Density"])
test

,Distance_km,HeightChange1,HeightChange2,HeightChange3,HeightChange4,Filter1,Filter2,Filter3,Accumulation_1,Accumulation_2,Accumulation_3,Accumulation_4,Snow_Density,Time_a,mean_without,mean_Filter1,mean_Filter2,mean_Filter3,Area,New_row
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pegelfeld,NaN
1,0.0,NaN,61.0,41.0,51.0,51.0,51.0,51.0,202.575000,202.575000,202.575000,202.575000,370.0,0.931507,NaN,NaN,NaN,NaN,km70/B30,71.170043
50,24.5,64.0,-11.0,NaN,26.5,26.5,26.5,26.5,107.627529,107.627529,107.627529,107.627529,385.0,0.947945,NaN,NaN,NaN,NaN,NaN,NaN
73,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,365.0,0.989041,NaN,NaN,NaN,NaN,NaN,NaN
261,130.0,40.0,34.0,NaN,37.0,37.0,37.0,37.0,157.558333,157.558333,157.558333,157.558333,420.0,0.986301,NaN,113.639201,113.639201,113.639201,NaN,NaN
352,175.5,11.0,NaN,NaN,11.0,11.0,11.0,11.0,53.533333,53.533333,53.533333,53.533333,480.0,0.986301,NaN,NaN,NaN,NaN,NaN,NaN
462,230.5,17.0,78.0,NaN,47.5,47.5,47.5,47.5,204.678819,204.678819,204.678819,204.678819,425.0,0.986301,NaN,NaN,NaN,NaN,NaN,NaN
552,275.5,68.0,NaN,NaN,68.0,68.0,68.0,68.0,313.697222,313.697222,313.697222,313.697222,455.0,0.986301,NaN,NaN,NaN,NaN,NaN,NaN
642,320.5,-4.0,-17.0,NaN,-10.5,-10.5,NaN,NaN,-46.841667,-46.841667,NaN,NaN,440.0,0.986301,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
# Setting a column as the indexes
index_test = test.set_index ("Snow_Density")
index_test

,Distance_km,HeightChange1,HeightChange2,HeightChange3,HeightChange4,Filter1,Filter2,Filter3,Accumulation_1,Accumulation_2,Accumulation_3,Accumulation_4,Time_a,mean_without,mean_Filter1,mean_Filter2,mean_Filter3,Area,New_row
Snow_Density,,,,,,,,,,,,,,,,,,,
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pegelfeld,NaN
370.0,0.0,NaN,61.0,41.0,51.0,51.0,51.0,51.0,202.575000,202.575000,202.575000,202.575000,0.931507,NaN,NaN,NaN,NaN,km70/B30,71.170043
385.0,24.5,64.0,-11.0,NaN,26.5,26.5,26.5,26.5,107.627529,107.627529,107.627529,107.627529,0.947945,NaN,NaN,NaN,NaN,NaN,NaN
365.0,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.989041,NaN,NaN,NaN,NaN,NaN,NaN
420.0,130.0,40.0,34.0,NaN,37.0,37.0,37.0,37.0,157.558333,157.558333,157.558333,157.558333,0.986301,NaN,113.639201,113.639201,113.639201,NaN,NaN
480.0,175.5,11.0,NaN,NaN,11.0,11.0,11.0,11.0,53.533333,53.533333,53.533333,53.533333,0.986301,NaN,NaN,NaN,NaN,NaN,NaN
425.0,230.5,17.0,78.0,NaN,47.5,47.5,47.5,47.5,204.678819,204.678819,204.678819,204.678819,0.986301,NaN,NaN,NaN,NaN,NaN,NaN
455.0,275.5,68.0,NaN,NaN,68.0,68.0,68.0,68.0,313.697222,313.697222,313.697222,313.697222,0.986301,NaN,NaN,NaN,NaN,NaN,NaN
440.0,320.5,-4.0,-17.0,NaN,-10.5,-10.5,NaN,NaN,-46.841667,-46.841667,NaN,NaN,0.986301,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
index_test.reset_index()

,Snow_Density,Distance_km,HeightChange1,HeightChange2,HeightChange3,HeightChange4,Filter1,Filter2,Filter3,Accumulation_1,Accumulation_2,Accumulation_3,Accumulation_4,Time_a,mean_without,mean_Filter1,mean_Filter2,mean_Filter3,Area,New_row
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pegelfeld,NaN
1,370.0,0.0,NaN,61.0,41.0,51.0,51.0,51.0,51.0,202.575000,202.575000,202.575000,202.575000,0.931507,NaN,NaN,NaN,NaN,km70/B30,71.170043
2,385.0,24.5,64.0,-11.0,NaN,26.5,26.5,26.5,26.5,107.627529,107.627529,107.627529,107.627529,0.947945,NaN,NaN,NaN,NaN,NaN,NaN
3,365.0,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.989041,NaN,NaN,NaN,NaN,NaN,NaN
4,420.0,130.0,40.0,34.0,NaN,37.0,37.0,37.0,37.0,157.558333,157.558333,157.558333,157.558333,0.986301,NaN,113.639201,113.639201,113.639201,NaN,NaN
5,480.0,175.5,11.0,NaN,NaN,11.0,11.0,11.0,11.0,53.533333,53.533333,53.533333,53.533333,0.986301,NaN,NaN,NaN,NaN,NaN,NaN
6,425.0,230.5,17.0,78.0,NaN,47.5,47.5,47.5,47.5,204.678819,204.678819,204.678819,204.678819,0.986301,NaN,NaN,NaN,NaN,NaN,NaN
7,455.0,275.5,68.0,NaN,NaN,68.0,68.0,68.0,68.0,313.697222,313.697222,313.697222,313.697222,0.986301,NaN,NaN,NaN,NaN,NaN,NaN
8,440.0,320.5,-4.0,-17.0,NaN,-10.5,-10.5,NaN,NaN,-46.841667,-46.841667,NaN,NaN,0.986301,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
# Drop an index
index_test2 = test
index_test2

,Distance_km,HeightChange1,HeightChange2,HeightChange3,HeightChange4,Filter1,Filter2,Filter3,Accumulation_1,Accumulation_2,Accumulation_3,Accumulation_4,Snow_Density,Time_a,mean_without,mean_Filter1,mean_Filter2,mean_Filter3,Area,New_row
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pegelfeld,NaN
1,0.0,NaN,61.0,41.0,51.0,51.0,51.0,51.0,202.575000,202.575000,202.575000,202.575000,370.0,0.931507,NaN,NaN,NaN,NaN,km70/B30,71.170043
50,24.5,64.0,-11.0,NaN,26.5,26.5,26.5,26.5,107.627529,107.627529,107.627529,107.627529,385.0,0.947945,NaN,NaN,NaN,NaN,NaN,NaN
73,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,365.0,0.989041,NaN,NaN,NaN,NaN,NaN,NaN
261,130.0,40.0,34.0,NaN,37.0,37.0,37.0,37.0,157.558333,157.558333,157.558333,157.558333,420.0,0.986301,NaN,113.639201,113.639201,113.639201,NaN,NaN
352,175.5,11.0,NaN,NaN,11.0,11.0,11.0,11.0,53.533333,53.533333,53.533333,53.533333,480.0,0.986301,NaN,NaN,NaN,NaN,NaN,NaN
462,230.5,17.0,78.0,NaN,47.5,47.5,47.5,47.5,204.678819,204.678819,204.678819,204.678819,425.0,0.986301,NaN,NaN,NaN,NaN,NaN,NaN
552,275.5,68.0,NaN,NaN,68.0,68.0,68.0,68.0,313.697222,313.697222,313.697222,313.697222,455.0,0.986301,NaN,NaN,NaN,NaN,NaN,NaN
642,320.5,-4.0,-17.0,NaN,-10.5,-10.5,NaN,NaN,-46.841667,-46.841667,NaN,NaN,440.0,0.986301,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
import os
os.getcwd()

'C:\\Users\\user\\Desktop\\TUT\\Data VIs and Analysis'

In [40]:
#In this case we have to set the index = False, to get the output correctly
df5.to_csv(r'C:\\Users\\user\\Desktop\\TUT\\Data VIs and Analysis\test1.csv', index = False)

In [41]:
print(df_dict_index)

                        0           1               2           3
name               Ginger       Scout          Barney       Buddy
breed           Dachshund   Dalmatian  French Bulldog     Maltese
height                 22          59              30          19
weight                 10          25              24           8
date_of_birth  2019-03-14  2008-03-23      2010-04-10  2016-04-21

In [42]:
print(df_dict_index.loc["name"])

0    Ginger
1     Scout
2    Barney
3     Buddy
Name: name, dtype: object

In [47]:
#Check the indexes. What indexes would you need to enter, to get the breed of "Ginger" and "Scout"?
print(df_dict_index.iloc[1:2, 0:2])

               0          1
breed  Dachshund  Dalmatian

In [48]:
df_dict_columns[df_dict_columns["name"].isin(["Ginger", "Barney"])]

     name           breed  height  weight date_of_birth
0  Ginger       Dachshund      22      10    2019-03-14
2  Barney  French Bulldog      30      24    2010-04-10

In [49]:

df2["Accumulation_1"]>100

0      False
1       True
2      False
3       True
4       True
5       True
6       True
7       True
8       True
9      False
10      True
11     False
12      True
13     False
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
       ...
873    False
874    False
875    False
876    False
877    False
878    False
879    False
880    False
881    False
882    False
883    False
884    False
885    False
886    False
887    False
888    False
889    False
890    False
891    False
892    False
893    False
894    False
895    False
896    False
897    False
898    False
899    False
900    False
901    False
902    False
Name: Accumulation_1, Length: 903, dtype: bool

In [52]:
df2[df2["Accumulation_1"]>400]

,Distance_km,HeightChange1,HeightChange2,HeightChange3,HeightChange4,Filter1,Filter2,Filter3,unknown_1,Accumulation_1,...,Snow_Density,Time_a,mean_without,mean_Filter1,mean_Filter2,mean_Filter3,unknown_2,Area,Area1,New_row
56,27.5,NaN,155.0,64.0,109.5,109.5,109.5,109.5,NaN,444.725072,...,385.0,0.947945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,29.5,NaN,127.0,NaN,127.0,127.0,127.0,127.0,NaN,515.799855,...,385.0,0.947945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,33.5,112.0,NaN,NaN,112.0,112.0,112.0,112.0,NaN,434.773481,...,385.0,0.991781,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,45.0,134.0,NaN,NaN,134.0,134.0,134.0,134.0,NaN,494.519391,...,365.0,0.989041,NaN,248.412959,248.412959,248.412959,248.412959,NaN,NaN,NaN
536,267.5,103.0,101.0,NaN,102.0,102.0,102.0,102.0,NaN,439.520833,...,425.0,0.986301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
537,268.0,101.0,105.0,NaN,103.0,103.0,103.0,103.0,NaN,443.829861,...,425.0,0.986301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
578,288.5,118.0,NaN,NaN,118.0,118.0,118.0,118.0,NaN,542.849031,...,455.0,0.989041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,295.5,93.0,NaN,NaN,93.0,93.0,93.0,93.0,NaN,427.838643,...,455.0,0.989041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
609,304.0,75.0,117.0,NaN,96.0,96.0,96.0,96.0,NaN,441.639889,...,455.0,0.989041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
625,312.0,86.0,91.0,NaN,88.5,88.5,88.5,88.5,NaN,408.267708,...,455.0,0.986301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
705,352.0,92.0,NaN,NaN,92.0,92.0,92.0,92.0,NaN,410.422222,...,440.0,0.986301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
715,357.0,81.0,126.0,NaN,103.5,103.5,103.5,103.5,NaN,461.725000,...,440.0,0.986301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
821,410.0,NaN,135.0,NaN,135.0,135.0,135.0,135.0,NaN,549.655512,...,425.0,1.043836,NaN,312.285761,312.285761,312.285761,312.285761,NaN,NaN,NaN

In [53]:
#Display only single columns (subsetting):
df2["Snow_Density"]

0        NaN
1      370.0
2      370.0
3      370.0
4      370.0
5      370.0
6      370.0
7      370.0
8      370.0
9      370.0
10     370.0
11     370.0
12     370.0
13     370.0
14     370.0
15     370.0
16     370.0
17     370.0
18     370.0
19     370.0
20     370.0
21     370.0
22     370.0
23     370.0
24     370.0
25     370.0
26     370.0
27     370.0
28     370.0
29     370.0
       ...
873      NaN
874      NaN
875      NaN
876      NaN
877      NaN
878      NaN
879      NaN
880      NaN
881      NaN
882      NaN
883      NaN
884      NaN
885      NaN
886      NaN
887      NaN
888      NaN
889      NaN
890      NaN
891      NaN
892      NaN
893      NaN
894      NaN
895      NaN
896      NaN
897      NaN
898      NaN
899      NaN
900      NaN
901      NaN
902      NaN
Name: Snow_Density, Length: 903, dtype: float64

In [54]:
#OR multiple columns (multiple subsetting):
df2[["Snow_Density", "Distance_km"]]

     Snow_Density  Distance_km
0             NaN          NaN
1           370.0          0.0
2           370.0          0.5
3           370.0          1.0
4           370.0          1.5
5           370.0          2.0
6           370.0          2.5
7           370.0          3.0
8           370.0          3.5
9           370.0          4.0
10          370.0          4.5
11          370.0          5.0
12          370.0          5.5
13          370.0          6.0
14          370.0          6.5
15          370.0          7.0
16          370.0          7.5
17          370.0          8.0
18          370.0          8.5
19          370.0          9.0
20          370.0          9.5
21          370.0         10.0
22          370.0         10.5
23          370.0         11.0
24          370.0         11.5
25          370.0         12.0
26          370.0         12.5
27          370.0         13.0
28          370.0         13.5
29          370.0         14.0
..            ...          ...
873           NaN        436.0
874           NaN        436.5
875           NaN        437.0
876           NaN        437.5
877           NaN        438.0
878           NaN        438.5
879           NaN        439.0
880           NaN        439.5
881           NaN        440.0
882           NaN        440.5
883           NaN        441.0
884           NaN        441.5
885           NaN        442.0
886           NaN        442.5
887           NaN        443.0
888           NaN        443.5
889           NaN        444.0
890           NaN        444.5
891           NaN        445.0
892           NaN        445.5
893           NaN        446.0
894           NaN        446.5
895           NaN        447.0
896           NaN        447.5
897           NaN        448.0
898           NaN        448.5
899           NaN        449.0
900           NaN        449.5
901           NaN        450.0
902           NaN          NaN

[903 rows x 2 columns]